CREATE TABLE IF NOT EXISTS `model`
(
    `id`         BIGINT       NOT NULL AUTO_INCREMENT PRIMARY KEY,
    `name`       VARCHAR(255) NOT NULL,
    `updated_at` TIMESTAMP    NOT NULL DEFAULT NOW()
);
